### ISSUE TITLE
support direct conversion from sskr to bip39

### ISSUE THREAD

**Issue by machadolab** [BlockchainCommons/seedtool-cli#61]
I confirmed this can convert a file of sskr shares back to bip39 correctly:

```
cat shares | seedtool --in sskr --out hex | seedtool --in hex --out bip39
```

but when trying to convert the same sskr shares file directly to bip39, I get:

```
cat shares | seedtool --in sskr --out bip39
seedtool: Input format sskr cannot be used with output format bip39
```

Is there a reason for this? 

Being able to convert directly from sskr to bip39 seems like one of the most common use cases. I want to provide sskr shares to my family members in case of an emergency and have a single command they can come together and run to convert this to a bip39 seed phrase that can be used by many wallets.

**Comment by wolfmcnally** [comment]
It would seriously complicate the design, coding, and testing of seedtool to be able to convert anything to anything. And since it is a command line tool that supports stdin and stdout and thus unix piping, I made the choice to keep its design simple and limit the conversions available to and from the most basic. If you have a particular common use case for you, just code up a single-line shell script.
